apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cron-example-multiple-binaries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-cron-example-multiple-binaries
  template:
    metadata:
      labels:
        app: kubernetes-cron-example-multiple-binaries
    spec:
      containers:
        - name: kubernetes-cron-example-multiple-binaries
          image: sevcandog/kubernetes-cron-example-multiple-binaries
          ports:
            - containerPort: 8080
