apiVersion: v1
kind: Service
metadata:
  name: kubernetes-cron-example-multiple-binaries-service
spec:
  selector:
    app: kubernetes-cron-example-multiple-binaries
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer